<Project>
<PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <AspNetCoreVersion>8.0.1</AspNetCoreVersion>
    <EntityFrameworkVersion>8.0.11</EntityFrameworkVersion>
    <MicrosoftExtensionsVersion>8.0.1</MicrosoftExtensionsVersion>
    <WilsonVersion>7.1.2</WilsonVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
      <AspNetCoreVersion>9.0.0</AspNetCoreVersion>
      <EntityFrameworkVersion>9.0.0</EntityFrameworkVersion>
      <MicrosoftExtensionsVersion>9.0.0</MicrosoftExtensionsVersion>
      <WilsonVersion>8.0.1</WilsonVersion>
  </PropertyGroup>

  <ItemGroup>
    <!--build related-->
    <PackageReference Include="MinVer" Version="2.3.0" PrivateAssets="All" />
    <PackageReference Update="SimpleExec" Version="6.2.0" />
    <PackageReference Update="Bullseye" Version="3.3.0" />
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />

    <!--tests -->
    <PackageReference Update="FluentAssertions" Version="5.10.2" />
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="16.2.0" />
    <PackageReference Update="xunit" Version="2.4.1" />
    <PackageReference Update="xunit.runner.visualstudio" Version="2.4.1" PrivateAssets="All" />

    <!--our stuff -->
    <PackageReference Update="IdentityModel" Version="7.0.0" />

    <!--microsoft extensions -->
    <PackageReference Update="Microsoft.Extensions.Caching.Memory" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Update="Microsoft.Extensions.Http" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Update="Microsoft.Extensions.Http.Polly" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Update="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Update="Microsoft.Extensions.Logging.Console" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Update="Microsoft.Extensions.Options.ConfigurationExtensions" Version="$(MicrosoftExtensionsVersion)" />
    
    <!--misc -->
    <PackageReference Update="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Update="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="$(WilsonVersion)" />
    <PackageReference Update="System.IdentityModel.Tokens.Jwt" Version="$(WilsonVersion)" />
    <PackageReference Update="System.Security.Principal.Windows" Version="5.0.0" />
    <PackageReference Update="AutoMapper" Version="12.0.1" />
    
    <!--microsoft asp.net core -->
    <PackageReference Update="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.AspNetCore.TestHost" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.AspNetCore.Identity" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.AspNetCore.Authentication.Certificate" Version="$(AspNetCoreVersion)"/>
    
    <!--microsoft entity framework -->
    <PackageReference Update="Microsoft.EntityFrameworkCore.Relational" Version="$(EntityFrameworkVersion)" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EntityFrameworkVersion)" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.InMemory" Version="$(EntityFrameworkVersion)" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.SqlServer" Version="$(EntityFrameworkVersion)" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Design" Version="$(EntityFrameworkVersion)" PrivateAssets="All" />

  </ItemGroup>

  <Target Name="SetAssemblyVersion" AfterTargets="MinVer">
    <PropertyGroup>
      <AssemblyVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch).0</AssemblyVersion>
    </PropertyGroup>
  </Target>
</Project>