name: 'NET8CI'

on:
  push:
    branches:
    - net8
    tags:
    - '*.*.*'
  pull_request:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
    - run: dotnet --info
    
    - if: (matrix.runs-on == 'windows-latest') && (github.ref == 'refs/heads/net8' || contains(github.ref, 'refs/tags/'))
      run: |
        ./build.ps1 quick
        dotnet nuget push .\nuget\*.nupkg -s https://nuget.pkg.github.com/ArcherTrister/index.json -k ${{ secrets.NUGETKEY }}