name: "publish"

on:
    push:
        tags:
            - "*.*.*"
    pull_request:

env:
    DOTNET_NOLOGO: true

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                runs-on: [windows-latest]
        name: ${{ matrix.runs-on }}
        runs-on: ${{ matrix.runs-on }}
        steps:
            - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
            - uses: actions/setup-dotnet@v4
              with:
                  global-json-file: ./global.json
            - run: dotnet --info
            - if: (matrix.runs-on == 'windows-latest') && (github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tags/'))
              run: |
                  ./rebuild.ps1
                  dotnet nuget push .\nuget\*.nupkg -s https://www.myget.org/F/archertrister/api/v2/package -k ${{ secrets.MYGET_KEY }}
